/*
 * File: app/store/Note.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TouchNote.store.Note', {
    extend: 'Ext.data.Store',

    requires: [
        'TouchNote.model.Note'
    ],

    config: {
        autoLoad: true,
        data: [
            {
                id: 1,
                content: 'Blog 1',
                categoryid: 1,
                category: 'Nonsense'
            },
            {
                id: 2,
                content: 'Blog 2',
                categoryid: 1,
                category: 'Nonsense'
            },
            {
                id: 3,
                content: 'Blog 3',
                categoryid: 2,
                category: 'Food'
            },
            {
                id: 4,
                content: 'Blog 4',
                categoryid: 2,
                category: 'Foodeee'
            }
        ],
        model: 'TouchNote.model.Note',
        storeId: 'NoteID',
        listeners: [
            {
                fn: 'onStoreLoad',
                event: 'load'
            }
        ]
    },

    onStoreLoad: function(store, records, successful, operation, eOpts) {
        console.log("Load Store");
    }

});