/*
 * File: app/view/MainNav.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TouchNote.view.MainNav', {
    extend: 'Ext.navigation.View',
    alias: 'widget.mainNav',

    requires: [
        'TouchNote.view.MainPanel'
    ],

    config: {
        fullscreen: true,
        id: 'mainNavv',
        itemId: '',
        autoDestroy: false,
        navigationBar: {
            id: 'navbar',
            layout: {
                pack: 'center',
                type: 'hbox'
            },
            items: [
                {
                    xtype: 'button',
                    flex: 1,
                    align: 'right',
                    id: 'addtest',
                    itemId: 'addbtn',
                    iconAlign: 'center',
                    iconCls: 'compose',
                    iconMask: true,
                    text: ''
                },
                {
                    xtype: 'button',
                    align: 'right',
                    hidden: true,
                    itemId: 'savebtn',
                    ui: 'action',
                    text: 'Save'
                }
            ]
        },
        items: [
            {
                xtype: 'mainpanel',
                title: '<div>Note List</div>'
            }
        ],
        listeners: [
            {
                fn: 'onAddNote',
                event: 'tap',
                delegate: '#addtest'
            },
            {
                fn: 'onSavebtnTap',
                event: 'tap',
                delegate: '#savebtn'
            },
            {
                fn: 'onMainNavvShow',
                event: 'show'
            },
            {
                fn: 'onMainNavvInitialize',
                event: 'initialize'
            },
            {
                fn: 'onMainNavvPop',
                event: 'pop'
            },
            {
                fn: 'onMainNavvPush',
                event: 'push'
            }
        ]
    },

    onAddNote: function(button, e, options) {
        console.log("Add Tap");
        this.fireEvent('addNoteCommand',this);
        console.log('Fire Event addNoteCommand');
    },

    onSavebtnTap: function(button, e, options) {
        console.log('Save Tap');
        //showAnimateion {type: 'fadeIn',duration: 200}
    },

    onMainNavvShow: function(component, options) {
        console.log('MainNav Show');
        var instance=Ext.ComponentQuery.query('mainNav')[0].id;
        console.log(instance);
    },

    onMainNavvInitialize: function(component, options) {
        console.log('MainNav Init');
        var instance=Ext.ComponentQuery.query('mainNav')[0].id;
        console.log(instance);

        var mainnav_instance=Ext.ComponentQuery.query('mainNav')[0];
        var notelist=Ext.ComponentQuery.query('mainpanel')[0];

        //mainnav_instance.setActiveItem(0);
        //mainnav_instance.push(notelist);

        if (Ext.os.is.Android){
            console.log('Android');
        }
        else{
            console.log('Window');
        }
    },

    onMainNavvPop: function(navigationView, view, options) {
        console.log('pop');
        navigationView.down('#addbtn').show();
        navigationView.down('#savebtn').hide();

    },

    onMainNavvPush: function(navigationView, view, options) {
        console.log('push');
        navigationView.down('#addbtn').hide();
        navigationView.down('#savebtn').show();

    }

});