/*
 * File: app/view/MainPanel.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TouchNote.view.MainPanel', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.mainpanel',

    config: {
        fullscreen: true,
        id: 'mainpanel',
        itemId: 'mainpanel',
        autoDestroy: false,
        items: [
            {
                xtype: 'container',
                title: 'NoteList',
                iconCls: 'home',
                itemId: 'notelistcontainer',
                layout: {
                    type: 'fit'
                },
                items: [
                    {
                        xtype: 'toolbar',
                        docked: 'top',
                        itemId: 'searchbar',
                        ui: 'light',
                        layout: {
                            align: 'center',
                            pack: 'end',
                            type: 'hbox'
                        },
                        items: [
                            {
                                xtype: 'searchfield',
                                flex: 1,
                                itemId: 'searchfield',
                                labelAlign: 'right',
                                placeHolder: 'Search'
                            },
                            {
                                xtype: 'button',
                                itemId: 'mybutton',
                                iconCls: 'favorites',
                                iconMask: true
                            }
                        ]
                    },
                    {
                        xtype: 'list',
                        height: '',
                        id: 'dataList',
                        itemId: 'notelist',
                        width: '',
                        layout: {
                            type: 'fit'
                        },
                        itemTpl: [
                            '<div>',
                            '    <div>{content}</div>',
                            '    <p>{category}</p>',
                            '</div>'
                        ],
                        scrollToTopOnRefresh: false,
                        store: 'NoteID',
                        onItemDisclosure: true
                    }
                ]
            }
        ],
        tabBar: {
            docked: 'bottom',
            layout: {
                pack: 'center',
                type: 'hbox'
            }
        },
        listeners: [
            {
                fn: 'onSearch',
                event: 'tap',
                delegate: '#mybutton'
            },
            {
                fn: 'onDataListDisclose',
                event: 'disclose',
                delegate: '#dataList'
            }
        ]
    },

    onSearch: function(button, e, options) {
        console.log("Search Tap");
    },

    onDataListDisclose: function(list, record, target, index, e, options) {
        console.log('Disclose');
        this.fireEvent('editNoteCommand', record);
        console.log('Fire Event editNoteCommand');
    }

});